run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - revive
    - gocyclo

gocyclo:
  min-complexity: 15


linters-settings:
  goanalysis_metalinter:
    enable: false
